#!/usr/bin/env bash

# Run a spell-checker on all staged content files, and
# stage any changes made.
#
# Acknowledgements:
#  - https://github.com/mprpic/git-spell-check
#  - https://stackoverflow.com/q/33610682/539599
#  - https://stackoverflow.com/a/10015707/539599
#  - https://stackoverflow.com/a/3879077/539599

set -u

exec < /dev/tty

for f in $(git diff --name-only --cached | grep content/); do
    if [ -f "${f}" ]; then
        echo "Spell-checking ${f} ... "
        aspell \
            --mode=sgml \
            --add-sgml-skip={ulink,code,literal,firstname,parameter,option,package,replaceable,programlisting,userinput,screen,filename,command,computeroutput,abbrev,accel,orgname,surname,foreignphrase,acronym,hardware,keycap,systemitem,application} \
            --lang="en" \
            --home-dir=. \
            check "${f}"
        if [[ $? != 0 ]]; then
            # Unfortunately, this never happens.
            # --> https://github.com/GNUAspell/aspell/issues/598
            echo 'Aborted.'
            exit 1
        else
            if ! git diff --quiet "${f}"; then
                echo "Staging changes to ${f}"
                git add "${f}"
            fi
        fi
    fi
done

if ! git diff --quiet .aspell*; then
    echo "Staging updated aspell dictionary"
    git add .aspell.*
fi

backup_count=$(find content -name '*.bak' | wc -l)
if [[ $backup_count -gt 0 ]]; then
    echo "Spell-check left ${backup_count} backup files behind."
    echo " --> find content -name '*.bak' | xargs rm"
fi
