#!/usr/bin/env bash

# Workaround for https://github.com/gohugoio/hugo/pull/6561
# inspired by: https://zipproth.de/cheat-sheets/hugo-asciidoctor/#_how_to_make_hugo_use_asciidoctor_with_extensions

# Get real asciidoctor:
# (credits: https://unix.stackexchange.com/a/108933/17409)
ad="$(
    PATH=":${PATH}:"
    PATH="${PATH//:$(pwd):/:}"
    PATH="${PATH#:}"
    PATH="${PATH%:}"
    which asciidoctor
)"

"${ad}" \
    --attribute=experimental=true \
    "$@"
