#!/usr/bin/env bash

# Workaround for https://github.com/gohugoio/hugo/pull/6561
# inspired by: https://zipproth.de/cheat-sheets/hugo-asciidoctor/#_how_to_make_hugo_use_asciidoctor_with_extensions
#
# This is only for local builds; CI/CD uses
# .github/scripts/reroute_asciidoctor.sh

# Get real asciidoctor:
# (credits: https://unix.stackexchange.com/a/108933/17409)
ad="$(
    PATH=":${PATH}:"
    PATH="${PATH//:$(pwd):/:}"
    PATH="${PATH#:}"
    PATH="${PATH%:}"
    which asciidoctor
)"

"${ad}" \
    --attribute=experimental=true \
    --attribute=icons=font \
    "$@"

# TODO: Disable web fonts? Is that even effective?
#    --attribute=webfonts! \
