name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
    pull_request:
      types:
        - opened
        - synchronize
        - reopened

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Setup asciidoctor
        uses: reitzig/actions-asciidoctor@master
        # TODO: @v1
        with:
          options: "-a experimental=true -a icons=font"

      - name: Build
        run: hugo --minify
        env:
          HUGO_ENV_PRIVATE_ADDRESS: "${{ secrets.HUGO_ENV_PRIVATE_ADDRESS }}"  
          HUGO_ENV_PRIVATE_USER:    "${{ secrets.HUGO_ENV_PRIVATE_USER }}"  
          HUGO_ENV_PRIVATE_DOMAIN:  "${{ secrets.HUGO_ENV_PRIVATE_DOMAIN }}"
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

